application:
  subdomain: composecraft
  background_task: false
  multi_instance: false
  upstreams:
    - location: /
      backend: http://saas:3000/
services:
  saas:
    # upstream: composecraft/composecraft:1.1.3
    image: docker.1ms.run/composecraft/composecraft:1.1.3
    environment:
      - CORE_ONLY=false
      - URL=http://composecraft.cloud.lazycat.app.composecraft.lzcapp:3000
      - SECRET_KEY={{ stable_secret "secret_key" }}
      - MONGODB_URI=mongodb://dev:{{ stable_secret "db_password" }}@db
      - DISABLE_TELEMETRY=true
    depends_on:
      - db
  db:
    # upstream: mongo:8.0.29
    image: docker.1ms.run/library/mongo:8.0.29
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD={{ stable_secret "db_password" }}
    binds:
      - /lzcapp/var/db:/data/db
