lzc-sdk-version: "0.1"
name: Compose Craft
package: cloud.lazycat.app.composecraft
version: 0.0.1
description: Compose craft 是一款工具，可以帮助您以图形用户界面 (GUI) 的方式管理、编辑和共享 Docker Compose 文件。
homepage: https://github.com/composecraft/composecraft
author: czyt
application:
  subdomain: composecraft
  background_task: false
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://saas.cloud.lazycat.app.composecraft.lzcapp:3000/
  ingress:
    - protocol: tcp
      port: 27017
      service: db
services:
  saas:
  # composecraft/composecraft:1.0.4

    image: registry.lazycat.cloud/czyt/composecraft/composecraft:f158d6cdbd7cc187
    environment:
      - CORE_ONLY=false
      - URL=http://composecraft.cloud.lazycat.app.composecraft.lzcapp:3000
      - SECRET_KEY=lazycat
      - MONGODB_URI=mongodb://dev:dev@db
      - DISABLE_TELEMETRY=true
    depends_on:
      - db
  db:
    image: registry.lazycat.cloud/czyt/library/mongo:6b0f3b8898c09d1d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev
    binds:
      - /lzcapp/var/db:/data/db
unsupported_platforms:
  - ios
  - android
